// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAz2oWbI6ULNG4QkmgTkbjkGPDpTDsNSc',
    appId: '1:1061942770542:web:ea35294658f335266bdf7f',
    messagingSenderId: '1061942770542',
    projectId: 'student-record-task2',
    authDomain: 'student-record-task2.firebaseapp.com',
    storageBucket: 'student-record-task2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEWLveJr2KfKFdZLJ54y6B4Fh4zUGb3dw',
    appId: '1:1061942770542:android:19f94670fc034bf86bdf7f',
    messagingSenderId: '1061942770542',
    projectId: 'student-record-task2',
    storageBucket: 'student-record-task2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVw2_PPhJhXklf1InnZFD77lnN9CtVZc',
    appId: '1:1061942770542:ios:24cd6b2f2cb301506bdf7f',
    messagingSenderId: '1061942770542',
    projectId: 'student-record-task2',
    storageBucket: 'student-record-task2.appspot.com',
    iosBundleId: 'com.example.studentsrecord1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVw2_PPhJhXklf1InnZFD77lnN9CtVZc',
    appId: '1:1061942770542:ios:24cd6b2f2cb301506bdf7f',
    messagingSenderId: '1061942770542',
    projectId: 'student-record-task2',
    storageBucket: 'student-record-task2.appspot.com',
    iosBundleId: 'com.example.studentsrecord1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAz2oWbI6ULNG4QkmgTkbjkGPDpTDsNSc',
    appId: '1:1061942770542:web:1656516d35b885436bdf7f',
    messagingSenderId: '1061942770542',
    projectId: 'student-record-task2',
    authDomain: 'student-record-task2.firebaseapp.com',
    storageBucket: 'student-record-task2.appspot.com',
  );

}