// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcLTtPh7Ihr-u9lUSpjQkYmqpCm93ri3I',
    appId: '1:985314319184:web:2fad3cc549ba2eb3532a55',
    messagingSenderId: '985314319184',
    projectId: 'crud-app-adi',
    authDomain: 'crud-app-adi.firebaseapp.com',
    storageBucket: 'crud-app-adi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4dSfnfOqDoLgAK0XzNABjdJaZ99fvOQ',
    appId: '1:985314319184:android:384ab5fd44bd642c532a55',
    messagingSenderId: '985314319184',
    projectId: 'crud-app-adi',
    storageBucket: 'crud-app-adi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EHuR4uC5WZv_-tvCoVzaN2104v2cnGM',
    appId: '1:985314319184:ios:83bcfb093e785aba532a55',
    messagingSenderId: '985314319184',
    projectId: 'crud-app-adi',
    storageBucket: 'crud-app-adi.appspot.com',
    iosBundleId: 'com.example.crudAppAdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EHuR4uC5WZv_-tvCoVzaN2104v2cnGM',
    appId: '1:985314319184:ios:83bcfb093e785aba532a55',
    messagingSenderId: '985314319184',
    projectId: 'crud-app-adi',
    storageBucket: 'crud-app-adi.appspot.com',
    iosBundleId: 'com.example.crudAppAdi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcLTtPh7Ihr-u9lUSpjQkYmqpCm93ri3I',
    appId: '1:985314319184:web:ea0866e62edb1082532a55',
    messagingSenderId: '985314319184',
    projectId: 'crud-app-adi',
    authDomain: 'crud-app-adi.firebaseapp.com',
    storageBucket: 'crud-app-adi.appspot.com',
  );
}
