// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlT1gx3fRxHre7jUfeObzidV_3rm29IKY',
    appId: '1:90120817384:web:4c4735299a056b77d9575d',
    messagingSenderId: '90120817384',
    projectId: 'tasknew-b6c17',
    authDomain: 'tasknew-b6c17.firebaseapp.com',
    storageBucket: 'tasknew-b6c17.appspot.com',
    measurementId: 'G-9TVDC0MD3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkl--U6qJcuieN94nLM7L4EEXf6TxOMlU',
    appId: '1:90120817384:android:f9eabb9060627bf7d9575d',
    messagingSenderId: '90120817384',
    projectId: 'tasknew-b6c17',
    storageBucket: 'tasknew-b6c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyKEnh5rQjsswm3S6uAou0TPeQaykBRk',
    appId: '1:90120817384:ios:6d895cb1733835fad9575d',
    messagingSenderId: '90120817384',
    projectId: 'tasknew-b6c17',
    storageBucket: 'tasknew-b6c17.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyKEnh5rQjsswm3S6uAou0TPeQaykBRk',
    appId: '1:90120817384:ios:6d895cb1733835fad9575d',
    messagingSenderId: '90120817384',
    projectId: 'tasknew-b6c17',
    storageBucket: 'tasknew-b6c17.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlT1gx3fRxHre7jUfeObzidV_3rm29IKY',
    appId: '1:90120817384:web:3739c94b0a6e8e7dd9575d',
    messagingSenderId: '90120817384',
    projectId: 'tasknew-b6c17',
    authDomain: 'tasknew-b6c17.firebaseapp.com',
    storageBucket: 'tasknew-b6c17.appspot.com',
    measurementId: 'G-7NZSNH9KM5',
  );
}
