// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmdHlWDvvVHvpd5yTGJIRyMolQp1KCK0',
    appId: '1:268784401813:web:45f36a7b4aac49e82cca9c',
    messagingSenderId: '268784401813',
    projectId: 'flteamsum',
    authDomain: 'flteamsum.firebaseapp.com',
    storageBucket: 'flteamsum.appspot.com',
    measurementId: 'G-4C7YLETZV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-rObahe-t1J-jVH4mRsNjD9YgVT12HQ',
    appId: '1:268784401813:android:24294028654da0a72cca9c',
    messagingSenderId: '268784401813',
    projectId: 'flteamsum',
    storageBucket: 'flteamsum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfahYlbZDEIsJzs3MQi5CNSWNwqHEylE',
    appId: '1:268784401813:ios:af7f8334f0ce34602cca9c',
    messagingSenderId: '268784401813',
    projectId: 'flteamsum',
    storageBucket: 'flteamsum.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfahYlbZDEIsJzs3MQi5CNSWNwqHEylE',
    appId: '1:268784401813:ios:af7f8334f0ce34602cca9c',
    messagingSenderId: '268784401813',
    projectId: 'flteamsum',
    storageBucket: 'flteamsum.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmdHlWDvvVHvpd5yTGJIRyMolQp1KCK0',
    appId: '1:268784401813:web:4c54fee3cd41156d2cca9c',
    messagingSenderId: '268784401813',
    projectId: 'flteamsum',
    authDomain: 'flteamsum.firebaseapp.com',
    storageBucket: 'flteamsum.appspot.com',
    measurementId: 'G-H03QMVY41M',
  );
}
